General:
  num_cpu: 2
  num_gpu: 1
  results_path: mil_model_aptc
Data:
  training_dataset_path: datasets/aptc-1/aptc_1_training_datatest.csv
  test_dataset_path: datasets/aptc-1/aptc_1_test_datatest.csv
  reactants: ['REACTANT_1', 'REACTANT_2']
  catalyst: ['CATALYST']
  activity: ['ACTIVITY']
Conformers:
  max_num_conf: 50
  energy_window: 50
Descriptors:
  num_descr: 3
Algorithm:
  type: InstanceWrapperMLPRegressor
  pooling: mean
  learning_rate: 0.001
  weight_decay: 0.001
  n_epoch: 1000
